# kubectl apply -f https://k8s.io/examples/pods/simple-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: test
spec:
  containers:
    - name: nginx
      image: "nginx:1.14.2"
      ports:
        - containerPort: 80
