apiVersion: v1
kind: Pod
metadata:
  name: nginx-probes
  namespace: test
spec:
  containers:
    - name: nginx
      image: "nginx:1.14.2"
      ports:
        - name: liveness-port
          containerPort: 80
      livenessProbe:
        httpGet:
          path: /
          port: liveness-port
        initialDelaySeconds: 3
        periodSeconds: 3
      startupProbe:
        httpGet:
          path: /
          port: liveness-port
        failureThreshold: 30
        periodSeconds: 10
